<?php

$scheme[DRIADA_WAREHOUSE_ID] = array(
    '236' => TREADMILL_CATEGORY_ID,
    '142' => TREADMILL_CATEGORY_ID,
    '165' => TREADMILL_CATEGORY_ID,
    '169' => TREADMILL_CATEGORY_ID,
    '237' => INDOOR_CYCLE_CATEGORY_ID,
    '143' => INDOOR_CYCLE_CATEGORY_ID,
    '156' => INDOOR_CYCLE_CATEGORY_ID,
    '166' => INDOOR_CYCLE_CATEGORY_ID,
    '170' => INDOOR_CYCLE_CATEGORY_ID,
    '238' => ELLIPTICAL_CATEGORY_ID,
    '152' => ELLIPTICAL_CATEGORY_ID,
    '168' => ELLIPTICAL_CATEGORY_ID,
    '171' => ELLIPTICAL_CATEGORY_ID,
);

return $scheme;
